### ISSUE TITLE
 ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client

### ISSUE THREAD

**Issue by cam-sam1715** [reportportal/example-java-TestNG#24] opened 2019-12-13 05:45 UTC
Hii i have installed reportpoartel in my localhost i am unable to pass my test results to Poartel

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
11:06:23.491 [main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
java.net.MalformedURLException: null
        at java.net.URL.<init>(URL.java:644)
        at java.net.URL.<init>(URL.java:507)
        at java.net.URL.<init>(URL.java:456)
        at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
        at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
        at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:68)
        at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:536)
        at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:87)
        at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:52)
        at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1048)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException: null
        at java.net.URL.<init>(URL.java:549)
        ... 18 common frames omitted
11:06:23.496 [main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:269)
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
        at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
        at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:68)
        at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:536)
        at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:87)
        at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:52)
        at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1048)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.MalformedURLException: null
        at java.net.URL.<init>(URL.java:644)
        at java.net.URL.<init>(URL.java:507)
        at java.net.URL.<init>(URL.java:456)
        at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
        ... 14 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.net.URL.<init>(URL.java:549)
        ... 18 common frames omitted

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.411 s
[INFO] Finished at: 2019-12-13T11:06:23+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project Test: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
[ERROR]         at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:254)
[ERROR]         at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
[ERROR]         at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:68)
[ERROR]         at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:536)
[ERROR]         at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:87)
[ERROR]         at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:52)
[ERROR]         at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
[ERROR]         at org.testng.TestNG.run(TestNG.java:1048)
[ERROR]         at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR]         at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR]         at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
[ERROR]         at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:269)
[ERROR]         at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
[ERROR]         ... 13 more
[ERROR] Caused by: java.net.MalformedURLException
[ERROR]         at java.net.URL.<init>(URL.java:644)
[ERROR]         at java.net.URL.<init>(URL.java:507)
[ERROR]         at java.net.URL.<init>(URL.java:456)
[ERROR]         at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
[ERROR]         at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
[ERROR]         ... 14 more
[ERROR] Caused by: java.lang.NullPointerException
[ERROR]         at java.net.URL.<init>(URL.java:549)
[ERROR]         ... 18 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by evjlobanova** [comment] 2019-12-17 13:11
Duplicate of https://github.com/reportportal/example-java-TestNG/issues/25
Follow the issue #25

**Closed by evjlobanova** 2019-12-17 13:11 UTC
